### ISSUE TITLE
error 가 있습니다.

### ISSUE THREAD

**Issue by Wooheelove** [yoonhohong/ncview#6]
안녕하십니까 교수님

ncviewer update 되어 행복합니다!!

raw data csv 로 파일 변환하여 upload 하는 과정에서 upload 는 complete 되나,

**An error has occurred. Check your logs or contact the app author for clarification.**

이런 문구가 떠서 혹시, 무엇이 문제 인지 잘 모르겠습니다.

기본 dataset form variables 가 아래 처럼 이전 data 에서 sensory NCS 만 추가한 form이 맞는지요?

Hosp | Date | Name | ID | Sex | Age | R.MM.DML | ... | L.TM.FL | L.MS.SNAP1 | L.MS.NCV1 | L.MS.SNAP2 | L.MS.NCV2 | L.MS.SNAP3 | L.MS.NCV3 | L.MS.SNAP4 | L.MS.NCV4 | L.US.SNAP1 | L.US.NCV1 | L.US.SNAP2 | L.US.NCV2 | L.US.SNAP3 | L.US.NCV3 | L.SS.SNAP1 | L.SS.NCV1

demo dataset 은 잘 되는 것 확인이 되는데 말이죠.

제가 뭘 잘못하고 있는 것인지.,,, 혹시 확인 부탁드려도 될지요?

감사합니다.

전공의  주우희 드림.

**Comment by yoonhohong** [comment]
내가 가진 파일은 upload 에 문제가 없는데... upload 하려는 파일 형식에 문제가 있을 수 있을 것 같네요. 내가 테스트해본 파일을 첨부하니, 한번 비교해보시고, 그래도 안되면 upload 하려는 파일을 나에게 전달해주세요. 
[CIDP_NCS_0115_DurCorrected.csv](https://github.com/yoonhohong/ncview/files/7322419/CIDP_NCS_0115_DurCorrected.csv)

**Comment by Wooheelove** [comment]
비교해보니, variables 순서가 이전에 보내주신 파일이랑 차이가 있어서 그런 것 같습니다.
우선 제가 순서만 조금 만져보면 될 것 같습니다.
감사합니다!!

전공의 주우희 드림.

2021년 10월 11일 (월) 오후 9:42, Hong, Yoonho ***@***.***>님이 작성:
